name: CI
on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-format-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python for pre-commit
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Run pre-commit (lint + format check)
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files
      - name: Run tests
        run: |
          chmod +x ./run_tests.sh
          ./run_tests.sh